Simulink.defineIntEnumType( 'DigitalLevel', ...
   {'IOHWAB_LOW','IOHWAB_HIGH'}, ...
   [0 1], ...
   'DefaultValue', 'IOHWAB_LOW', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

