Simulink.defineIntEnumType( 'SignalQuality', ...
   {'IOHWAB_INIVAL','IOHWAB_ERR','IOHWAB_BAD','IOHWAB_GOOD'}, ...
   [0 1 2 3], ...
   'DefaultValue', 'IOHWAB_INIVAL', ...
   'StorageType', 'uint8', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

